
[functions.delete-old-completed-tasks]
enabled = true
verify_jwt = true
import_map = "./functions/delete-old-completed-tasks/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-old-completed-tasks/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-old-completed-tasks/*.html" ]

[functions.reset-expired-quotas]
enabled = true
verify_jwt = true
import_map = "./functions/reset-expired-quotas/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reset-expired-quotas/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reset-expired-quotas/*.html" ]
